// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX7q9nBLu_gb-1km5FxnlBwxih5H1v9pU',
    appId: '1:597724033130:web:f5ed8132a68cc73b09da13',
    messagingSenderId: '597724033130',
    projectId: 'cmsc23-donation-system',
    authDomain: 'cmsc23-donation-system.firebaseapp.com',
    storageBucket: 'cmsc23-donation-system.appspot.com',
    measurementId: 'G-R8P6YMPMPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDle83JJbCxPo4v47VsbZZPPKyqo59Hpc',
    appId: '1:597724033130:android:1eae01e926e01d1209da13',
    messagingSenderId: '597724033130',
    projectId: 'cmsc23-donation-system',
    storageBucket: 'cmsc23-donation-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuIRsLr8fuZPirmbj-ClDNMOdkxKEn_xM',
    appId: '1:597724033130:ios:e7a9237b2ef5ef9809da13',
    messagingSenderId: '597724033130',
    projectId: 'cmsc23-donation-system',
    storageBucket: 'cmsc23-donation-system.appspot.com',
    iosBundleId: 'com.example.elbiDonationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuIRsLr8fuZPirmbj-ClDNMOdkxKEn_xM',
    appId: '1:597724033130:ios:e7a9237b2ef5ef9809da13',
    messagingSenderId: '597724033130',
    projectId: 'cmsc23-donation-system',
    storageBucket: 'cmsc23-donation-system.appspot.com',
    iosBundleId: 'com.example.elbiDonationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX7q9nBLu_gb-1km5FxnlBwxih5H1v9pU',
    appId: '1:597724033130:web:b7d11b749a131bb109da13',
    messagingSenderId: '597724033130',
    projectId: 'cmsc23-donation-system',
    authDomain: 'cmsc23-donation-system.firebaseapp.com',
    storageBucket: 'cmsc23-donation-system.appspot.com',
    measurementId: 'G-88DD345D0H',
  );

}